default: &default
  adapter:  postgresql
  encoding: unicode

development:
  <<: *default
  database: isc-434_development

test:
  <<: *default
  database: isc-434_test

production:
  <<: *default
  database: isc-434_production